In [1]:
import pandas as pd
import numpy as np

In [3]:
# Get Pandas Version

pd.__version__

'3.0.5'

In [4]:
# Read CSV

df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

# Get the Length of the dataset df
len(df)

10000

In [5]:
# Get number of distinct fuel_type

df.fuel_type.nunique()

3

In [6]:
# Get Columns with Missing Values

df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
# Get maximum fuel efficiency of cars from Asia

df[df.origin.str.lower() == 'asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

In [8]:
# Get the median value of the horsepower column => median()

df.horsepower.median()

np.float64(254.0)

In [9]:
# Get the most frequent value of the horsepower column => mode()

df.horsepower.mode()[0]

np.float64(252.0)

In [10]:
# Number of Missing Values Before

df.horsepower.isnull().sum()

np.int64(877)

In [11]:
# Update Missing values in horsepower with the Most Frequent Value of the Column

df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [12]:
# Number of Missing Values After

df.horsepower.isnull().sum()

np.int64(0)

In [13]:
# Get the new median value of the horsepower column => median()

df.horsepower.median()

np.float64(252.0)

In [20]:
# Sum of weights

X = df[df.origin.str.lower()=='asia'][['vehicle_weight','model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [24]:
# Transpose of X

XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [27]:
# Transpose of X * X

XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [29]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [33]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

w = (XTX_inv.dot(XT)).dot(y)
np.sum(w)

np.float64(0.36919696904925486)

In [5]:
# Describe Dataframe

df.describe() # It only prints the stats of numeric columns

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [6]:
# Get top 5 rows

df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
# Get distinct fuel_type

df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [9]:
df.isnull()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False